package com.vsh.uvc
// Warning! This file is autogenerated.
// Source file ../../../../../../../cgen/enums.kts

enum class UvcAdjustements(val rawValue: Int) {
    PANTILT(1),
    BRIGHTNESS(2),
    CONTRAST(3),
    HUE(4),
    SATURATION(5),
    SHARPNESS(6),
    GAMMA(7),
    WB_TEMP(8),
    WB_COMPO(9),
    BACKLIGHT(10),
    GAIN(11),
    POWERLINE_LF(12)
}
