name: CMake test C++

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get install -y libx264-dev libgtk-4-dev libportaudio2 portaudio19-dev libavcodec-dev libavformat-dev libavutil-dev pkg-config
        
    - name: Prepare build
      run: python workflow_build.py --prepare

    - name: Build
      run: python workflow_build.py --build

    - name: Tests
      run: python workflow_build.py --test